steps:
name: PowerShell Publish
on: [push]
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
      
    - name: Add private GitHub registry to NuGet
      run: nuget sources add -name "PSScripts" -Source https://nuget.pkg.github.com/bjd145/index.json -Username bjd145 -Password ${{ secrets.MY_GITHUB_TOKEN }}
       
    - name: Nuget Pack
      run: nuget pack *.nuspec

    - name: Nuget Push
      run: nuget push *.nupkg -Source "PSScripts" -SkipDuplicate
